from sqlalchemy import create_engine, text

try:

    engine = create_engine("mysql+pymysql://root:@localhost/diagnostico_db")
    with engine.connect() as connection:
        result = connection.execute(text("SELECT 1"))
        print("Conex達o com SQLAlchemy bem-sucedida:", result.fetchone())
except Exception as e:
    print("Erro na conex達o com SQLAlchemy:", str(e))

try:
    import mysql.connector
    cnx = mysql.connector.connect(
        user='root',
        password='',
        host='localhost',
        database='diagnostico_db'
    )
    print("Conex達o direta com mysql-connector-python bem-sucedida")
    cnx.close()
except Exception as err:
    print("Erro na conex達o direta com mysql-connector-python:", str(err))